//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.19 at 08:53:38 PM MESZ 
//


package de.rollercoaster.data.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{xml-schema-rollercoaster.xsd}General"/>
 *         &lt;element ref="{xml-schema-rollercoaster.xsd}SimulationParameters" minOccurs="0"/>
 *         &lt;element ref="{xml-schema-rollercoaster.xsd}PillarList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "general",
    "simulationParameters",
    "pillarList"
})
@XmlRootElement(name = "Track")
public class Track {

    @XmlElement(name = "General", required = true)
    protected General general;
    @XmlElement(name = "SimulationParameters")
    protected SimulationParameters simulationParameters;
    @XmlElement(name = "PillarList", required = true)
    protected PillarList pillarList;

    /**
     * Gets the value of the general property.
     * 
     * @return
     *     possible object is
     *     {@link General }
     *     
     */
    public General getGeneral() {
        return general;
    }

    /**
     * Sets the value of the general property.
     * 
     * @param value
     *     allowed object is
     *     {@link General }
     *     
     */
    public void setGeneral(General value) {
        this.general = value;
    }

    /**
     * Gets the value of the simulationParameters property.
     * 
     * @return
     *     possible object is
     *     {@link SimulationParameters }
     *     
     */
    public SimulationParameters getSimulationParameters() {
        return simulationParameters;
    }

    /**
     * Sets the value of the simulationParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimulationParameters }
     *     
     */
    public void setSimulationParameters(SimulationParameters value) {
        this.simulationParameters = value;
    }

    /**
     * Gets the value of the pillarList property.
     * 
     * @return
     *     possible object is
     *     {@link PillarList }
     *     
     */
    public PillarList getPillarList() {
        return pillarList;
    }

    /**
     * Sets the value of the pillarList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PillarList }
     *     
     */
    public void setPillarList(PillarList value) {
        this.pillarList = value;
    }

}
