//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.19 at 08:53:38 PM MESZ 
//


package de.rollercoaster.data.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PosX" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="PosY" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="PosZ" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="YawX" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="YawY" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="YawZ" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="YawAngle" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "posX",
    "posY",
    "posZ",
    "yawX",
    "yawY",
    "yawZ",
    "yawAngle"
})
@XmlRootElement(name = "Pillar")
public class Pillar {

    @XmlElement(name = "PosX")
    protected double posX;
    @XmlElement(name = "PosY")
    protected double posY;
    @XmlElement(name = "PosZ")
    protected double posZ;
    @XmlElement(name = "YawX")
    protected double yawX;
    @XmlElement(name = "YawY")
    protected double yawY;
    @XmlElement(name = "YawZ")
    protected double yawZ;
    @XmlElement(name = "YawAngle")
    protected double yawAngle;

    /**
     * Gets the value of the posX property.
     * 
     */
    public double getPosX() {
        return posX;
    }

    /**
     * Sets the value of the posX property.
     * 
     */
    public void setPosX(double value) {
        this.posX = value;
    }

    /**
     * Gets the value of the posY property.
     * 
     */
    public double getPosY() {
        return posY;
    }

    /**
     * Sets the value of the posY property.
     * 
     */
    public void setPosY(double value) {
        this.posY = value;
    }

    /**
     * Gets the value of the posZ property.
     * 
     */
    public double getPosZ() {
        return posZ;
    }

    /**
     * Sets the value of the posZ property.
     * 
     */
    public void setPosZ(double value) {
        this.posZ = value;
    }

    /**
     * Gets the value of the yawX property.
     * 
     */
    public double getYawX() {
        return yawX;
    }

    /**
     * Sets the value of the yawX property.
     * 
     */
    public void setYawX(double value) {
        this.yawX = value;
    }

    /**
     * Gets the value of the yawY property.
     * 
     */
    public double getYawY() {
        return yawY;
    }

    /**
     * Sets the value of the yawY property.
     * 
     */
    public void setYawY(double value) {
        this.yawY = value;
    }

    /**
     * Gets the value of the yawZ property.
     * 
     */
    public double getYawZ() {
        return yawZ;
    }

    /**
     * Sets the value of the yawZ property.
     * 
     */
    public void setYawZ(double value) {
        this.yawZ = value;
    }

    /**
     * Gets the value of the yawAngle property.
     * 
     */
    public double getYawAngle() {
        return yawAngle;
    }

    /**
     * Sets the value of the yawAngle property.
     * 
     */
    public void setYawAngle(double value) {
        this.yawAngle = value;
    }

}
