//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.19 at 08:53:38 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "xml-schema-rollercoaster.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.rollercoaster.data.xml;
